language: python
python:
- 3.8
install:
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  username: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDBjYTBkMDNjLWEzODQtNDEwZC05NzdjLWMwN2M5Y2UxNWU4NQACOHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJ4c3BsaW5lIl19LCAidmVyc2lvbiI6IDF9AAAGIA3YHDaIpJIa27Z-yOgwMv9hLARUAzsN3r1yGwgbe7Gs
  on:
    branch: main
    repo: zhengp0/xspline
    tags: true
