language: python
python:
- 3.8
install:
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: redoWX2Gbq8gHCmQ3N5g3Gs5mPBHNz7aUJxgA8U735PEnipHTJzeFIorbtyqKVEsOZt7ZpU6nSe3IHtR0SEEnvgBO/Na8emx/YDGj4iLQzsMO0rCENIaiijmMLpKWuTgydXzcCs6DvRXNgCKYf1dlWD/ZE4VPwSmqFeCI+W1TPvHY6YkLenauyEFtlrwlD2sFy+nFZ1o6cvqo5Pr+XhZJHAa80JGs57/nokC/GsCovYgc5u8wBMEwAEO9pVaLSais5WkFDNzSJEzchojQwLrONdTp8Kfs7+cxy353XxW04CzxEp2zz8f2qwaas9ZmwN/5k5W8ZfIpYB1im5YHo9P6Xwm941ICKoV6Y3RttXB7PkqOrz3nCmI0uLWY5yQmYA9yuhRHrpbGl8d/WK6kxkfjjtprYctK6FnC9EFlDqApMmeJVqXEUMxKlR7fbME9jctlPdpJpBTftjfYbfG4XdWFZKY7cfZzCLoc+pj6oUm8MVqAZfJWuIyuIB+oCgIck2t9tWDqFeIuneW2DplXV4y3qEPP61vluwkM7lwTFcOGDFpP3KyHqHzRaSqya5qBN3VmpJ/d1eVCfNHOao+mdjBxDgG20AN8lUfZYB8UGMuBo2hOnQO1iuKfoi64AuFYRtZ0fcKL0/9gEdO9SvagGzsRo0GdUs+mCAvEji4beSwOSg=
  on:
    branch: main
    repo: zhengp0/xspline
    tags: true
