name: Build & Publish Docs with Sphinx

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install .[docs] --upgrade pip
      - name: Generate API docs & Build sphinx documentation
        run: |
          cd docs
          make clean
          make html
          cd ..
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
          ssk-key: ${{ secrets.DEPLOY_KEY }}