name: python-build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install .[dev] --upgrade pip
    - name: Test with pytest
      run: pytest

  deploy:

    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build package distribution
      run: |
        python -m pip install build --upgrade pip
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish package distribution to PyPI
      uses: pypa/gh-action-pypi-publish@main
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
